#!/usr/bin/env python3
"""
Connectome geometry + projection-grid baseline analysis for a VDM run (1k snapshots).

This is *offline* analysis: it builds a coordinate system from the connectome itself (spectral embedding),
detects communities (Louvain), computes node participation coefficients, and then bins nodes into a 32×32
"projection grid" in the embedding space. The grid is populated with the stationary random-walk density π,
which serves as a baseline for what a walk-driven projection map would look like at equilibrium.

Intended use:
- Provide a geometry/coordinate frame for later "walker glow / projection map" observability.
- Provide baseline density maps and identify candidate convergence zones (hubs spanning communities).

Inputs expected inside run_dir:
- state_*.h5 (CSR topology: row_ptr, col_idx; per-row weight parameter W)

Outputs:
- CSVs + PNG plots in out_dir
- sha256 indexes in out_dir/provenance

Author: generated by assistant for reproducibility.
"""
from __future__ import annotations
import argparse, json, hashlib
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.sparse as sp
import scipy.sparse.linalg as spla
import scipy.stats as stats
import networkx as nx
import h5py

def sha256_file(path: Path, chunk=1<<20) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            b = f.read(chunk)
            if not b:
                break
            h.update(b)
    return h.hexdigest()

def gini(x: np.ndarray) -> float:
    x = np.asarray(x, dtype=float)
    x = x[np.isfinite(x)]
    if len(x) == 0:
        return float("nan")
    if np.all(x == 0):
        return 0.0
    x_sorted = np.sort(x)
    n = len(x_sorted)
    cumx = np.cumsum(x_sorted)
    return (n + 1 - 2*np.sum(cumx)/cumx[-1]) / n

def load_csr_with_rowweights(h5_path: Path) -> tuple[sp.csr_matrix, np.ndarray]:
    with h5py.File(h5_path, "r") as h5:
        row_ptr = h5["sparse/row_ptr"][:].astype(np.int64)
        col_idx = h5["sparse/col_idx"][:].astype(np.int64)
        Wrow = h5["sparse/W"][:].astype(np.float64)  # per-row weight parameter
    N = len(row_ptr) - 1
    out_deg = np.diff(row_ptr)
    data = np.repeat(Wrow, out_deg)
    A = sp.csr_matrix((data, col_idx, row_ptr), shape=(N, N))
    return A, Wrow

def stationary_distribution(A: sp.csr_matrix, tol=1e-12, maxit=50000, teleport=1e-6) -> np.ndarray:
    """
    Stationary distribution for a weighted random walk on directed A.
    Uses tiny teleportation to ensure ergodicity.
    """
    N = A.shape[0]
    out_w = np.array(A.sum(axis=1)).ravel()
    inv_out = np.zeros(N)
    m = out_w > 0
    inv_out[m] = 1.0 / out_w[m]
    AT = A.transpose().tocsr()

    pi = np.full(N, 1.0/N, dtype=float)
    for _ in range(maxit):
        tmp = pi * inv_out
        nxt = AT.dot(tmp)
        dangling = pi[~m].sum() if np.any(~m) else 0.0
        if dangling:
            nxt += dangling / N
        nxt = (1-teleport)*nxt + teleport*(1.0/N)
        s = nxt.sum()
        if s != 0:
            nxt /= s
        if np.linalg.norm(nxt - pi, 1) < tol:
            pi = nxt
            break
        pi = nxt
    return pi

def spectral_embedding(A_sym: sp.csr_matrix, n_components=3, seed=0):
    """
    Spectral embedding from normalized Laplacian of the symmetrized graph.
    Returns smallest eigenvalues (including the ~0 trivial) and coordinates (skip trivial).
    """
    N = A_sym.shape[0]
    deg = np.array(A_sym.sum(axis=1)).ravel()
    d_inv_sqrt = np.zeros_like(deg)
    m = deg > 0
    d_inv_sqrt[m] = 1.0 / np.sqrt(deg[m])
    D_inv_sqrt = sp.diags(d_inv_sqrt)
    L = sp.eye(N, format="csr") - D_inv_sqrt @ A_sym @ D_inv_sqrt

    k = n_components + 1
    rng = np.random.default_rng(seed)
    v0 = rng.normal(size=N)
    vals, vecs = spla.eigsh(L, k=k, which="SM", tol=1e-3, maxiter=10000, v0=v0)
    idx = np.argsort(vals)
    vals = vals[idx]
    vecs = vecs[:, idx]
    coords = vecs[:, 1:n_components+1]
    return vals, coords

def louvain_communities(A_sym: sp.csr_matrix, seed=0):
    G = nx.from_scipy_sparse_array(A_sym, edge_attribute="weight")
    comms = nx.algorithms.community.louvain_communities(G, weight="weight", seed=seed, resolution=1.0)
    node_to_c = np.zeros(G.number_of_nodes(), dtype=int)
    for i, cs in enumerate(comms):
        for n in cs:
            node_to_c[n] = i
    return comms, node_to_c

def participation_coefficient(A_sym: sp.csr_matrix, node_to_c: np.ndarray) -> np.ndarray:
    N = A_sym.shape[0]
    deg = np.array(A_sym.sum(axis=1)).ravel()
    nc = node_to_c.max() + 1
    P = np.zeros(N, dtype=float)
    for i in range(N):
        ki = deg[i]
        if ki <= 0:
            continue
        start, end = A_sym.indptr[i], A_sym.indptr[i+1]
        neigh = A_sym.indices[start:end]
        w = A_sym.data[start:end]
        comm = node_to_c[neigh]
        sums = np.bincount(comm, weights=w, minlength=nc)
        P[i] = 1.0 - np.sum((sums/ki)**2)
    return P

def gridify(coords2d: np.ndarray, values: np.ndarray, grid_size=32, padding=0.02):
    x = coords2d[:, 0]
    y = coords2d[:, 1]
    xmin, xmax = x.min(), x.max()
    ymin, ymax = y.min(), y.max()
    xr = xmax - xmin
    yr = ymax - ymin
    xmin -= padding * xr
    xmax += padding * xr
    ymin -= padding * yr
    ymax += padding * yr
    xn = (x - xmin) / (xmax - xmin + 1e-12)
    yn = (y - ymin) / (ymax - ymin + 1e-12)
    xi = np.clip((xn * grid_size).astype(int), 0, grid_size-1)
    yi = np.clip((yn * grid_size).astype(int), 0, grid_size-1)

    grid = np.zeros((grid_size, grid_size), dtype=float)
    counts = np.zeros((grid_size, grid_size), dtype=int)
    for v, i, j in zip(values, xi, yi):
        grid[j, i] += float(v)
        counts[j, i] += 1
    meta = {"xmin": float(xmin), "xmax": float(xmax), "ymin": float(ymin), "ymax": float(ymax)}
    return grid, counts, meta

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run_dir", type=str, required=True, help="Path to run directory containing state_*.h5 snapshots")
    ap.add_argument("--out_dir", type=str, required=True, help="Output directory")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--grid_size", type=int, default=32)
    args = ap.parse_args()

    run_dir = Path(args.run_dir)
    out_dir = Path(args.out_dir)
    plots_dir = out_dir / "plots"
    results_dir = out_dir / "results"
    prov_dir = out_dir / "provenance"
    scripts_dir = out_dir / "scripts"
    for d in [plots_dir, results_dir, prov_dir, scripts_dir]:
        d.mkdir(parents=True, exist_ok=True)

    state_files = sorted(run_dir.glob("state_*.h5"))
    if not state_files:
        raise SystemExit(f"No state_*.h5 found in {run_dir}")

    # provenance: input hashes
    input_rows = [{"path": str(p), "sha256": sha256_file(p)} for p in state_files]
    pd.DataFrame(input_rows).to_csv(prov_dir/"raw_input_sha256.csv", index=False)

    rows = []
    node_tables = []

    for sf in state_files:
        A, Wrow = load_csr_with_rowweights(sf)
        N = A.shape[0]
        out_deg = np.diff(A.indptr)
        in_deg = np.bincount(A.indices, minlength=N)
        out_w = np.array(A.sum(axis=1)).ravel()
        in_w = np.array(A.sum(axis=0)).ravel()

        A_sym = (A + A.transpose()) * 0.5
        pi = stationary_distribution(A)
        eigvals, coords = spectral_embedding(A_sym, n_components=3, seed=args.seed)
        comms, node_to_c = louvain_communities(A_sym, seed=args.seed)
        part = participation_coefficient(A_sym, node_to_c)

        # pagerank
        Gd = nx.from_scipy_sparse_array(A, edge_attribute="weight", create_using=nx.DiGraph)
        pr = nx.pagerank(Gd, alpha=0.85, tol=1e-12, max_iter=5000, weight="weight")
        pr_vec = np.array([pr[i] for i in range(N)])

        # convergence score: z(log degree) + z(participation)
        z_deg = (np.log1p(out_deg) - np.log1p(out_deg).mean()) / (np.log1p(out_deg).std() + 1e-12)
        z_part = (part - part.mean()) / (part.std() + 1e-12)
        conv_score = z_deg + z_part

        df = pd.DataFrame({
            "node": np.arange(N),
            "out_degree": out_deg,
            "in_degree": in_deg,
            "out_weight": out_w,
            "in_weight": in_w,
            "pi_stationary": pi,
            "emb1": coords[:, 0],
            "emb2": coords[:, 1],
            "emb3": coords[:, 2],
            "community": node_to_c,
            "participation": part,
            "pagerank": pr_vec,
            "convergence_score": conv_score,
            "row_weight_param": Wrow,
        })
        node_tables.append((sf.stem, df))

        rows.append({
            "snapshot": sf.stem,
            "sha256": sha256_file(sf),
            "N": N,
            "E": int(A.nnz),
            "out_degree_mean": float(out_deg.mean()),
            "out_degree_median": float(np.median(out_deg)),
            "out_degree_max": int(out_deg.max()),
            "gini_out_degree": float(gini(out_deg)),
            "gini_pi_stationary": float(gini(pi)),
            "n_communities": int(len(comms)),
            "spectral_eigvals_smallest": ",".join([f"{v:.6g}" for v in eigvals[:8]]),
        })

        # per-snapshot files
        df.to_csv(results_dir/f"node_embedding_metrics_{sf.stem}.csv", index=False)

        comm_sizes = df.groupby("community")["node"].count().reset_index(name="size").sort_values("size", ascending=False)
        comm_sizes.to_csv(results_dir/f"community_sizes_{sf.stem}.csv", index=False)

        top = df.sort_values("convergence_score", ascending=False).head(50)[["node","out_degree","participation","pagerank","convergence_score","community"]]
        top.to_csv(results_dir/f"top_convergence_nodes_{sf.stem}.csv", index=False)

        # baseline grid
        coords2d = df[["emb1","emb2"]].to_numpy()
        grid, counts, meta = gridify(coords2d, df["pi_stationary"].to_numpy(), grid_size=args.grid_size)
        rows_grid = []
        for r in range(grid.shape[0]):
            for c in range(grid.shape[1]):
                rows_grid.append({"row": r, "col": c, "pi_density": grid[r, c], "n_nodes": int(counts[r, c])})
        pd.DataFrame(rows_grid).to_csv(results_dir/f"baseline_projection_grid_pi_{sf.stem}_{args.grid_size}x{args.grid_size}.csv", index=False)
        with open(results_dir/f"baseline_projection_grid_pi_{sf.stem}_{args.grid_size}x{args.grid_size}_meta.json","w") as f:
            json.dump(meta, f, indent=2)

        # plots
        deg = df["out_degree"].to_numpy()
        deg_pos = deg[deg > 0]
        x_sorted = np.sort(deg_pos)
        ccdf = 1.0 - np.arange(1, len(x_sorted)+1)/len(x_sorted)
        plt.figure(figsize=(6, 4))
        plt.loglog(x_sorted, ccdf, marker=".", linestyle="none")
        plt.xlabel("out-degree k")
        plt.ylabel("CCDF P(K>=k)")
        plt.title(f"Out-degree CCDF (log-log) {sf.stem}")
        plt.tight_layout()
        plt.savefig(plots_dir/f"degree_ccdf_loglog_{sf.stem}.png", dpi=180)
        plt.close()

        plt.figure(figsize=(6, 5))
        sizes = 10 + 30*(np.log1p(df["out_degree"])/np.log1p(df["out_degree"].max()+1e-12))
        plt.scatter(df["emb1"], df["emb2"], c=df["community"], s=sizes, alpha=0.7)
        plt.xlabel("spectral emb1")
        plt.ylabel("spectral emb2")
        plt.title(f"Spectral embedding colored by community {sf.stem}")
        plt.tight_layout()
        plt.savefig(plots_dir/f"embedding_scatter_community_{sf.stem}.png", dpi=180)
        plt.close()

        plt.figure(figsize=(5, 4))
        plt.imshow(grid, origin="lower", aspect="auto")
        plt.colorbar(label="sum stationary probability in cell")
        plt.title(f"Baseline projection grid (pi) {sf.stem}")
        plt.tight_layout()
        plt.savefig(plots_dir/f"baseline_pi_heatmap_{sf.stem}_{args.grid_size}x{args.grid_size}.png", dpi=180)
        plt.close()

    summary = pd.DataFrame(rows)
    summary.to_csv(results_dir/"connectome_geometry_summary_across_snapshots.csv", index=False)

    # cross snapshot comparisons
    snap_names = [name for name, _ in node_tables]
    deg_sorted = {name: np.sort(df["out_degree"].to_numpy()) for name, df in node_tables}
    ks_mat = np.zeros((len(snap_names), len(snap_names)))
    for i, ni in enumerate(snap_names):
        for j, nj in enumerate(snap_names):
            if i == j:
                ks_mat[i, j] = 0.0
            elif i < j:
                ks_mat[i, j] = stats.ks_2samp(deg_sorted[ni], deg_sorted[nj]).statistic
            else:
                ks_mat[i, j] = ks_mat[j, i]
    pd.DataFrame(ks_mat, index=snap_names, columns=snap_names).to_csv(results_dir/"degree_distribution_ks_matrix.csv")

    deg_arrays = {name: df.sort_values("node")["out_degree"].to_numpy() for name, df in node_tables}
    corr_rows = []
    for i in range(len(snap_names)):
        for j in range(i+1, len(snap_names)):
            a = deg_arrays[snap_names[i]]
            b = deg_arrays[snap_names[j]]
            corr_rows.append({
                "snap_i": snap_names[i],
                "snap_j": snap_names[j],
                "pearson": float(np.corrcoef(a, b)[0, 1]),
                "spearman": float(stats.spearmanr(a, b).correlation),
            })
    corr_df = pd.DataFrame(corr_rows)
    corr_df.to_csv(results_dir/"nodewise_degree_correlations.csv", index=False)

    # heatmap KS
    plt.figure(figsize=(6, 5))
    plt.imshow(ks_mat, origin="lower", aspect="auto")
    plt.xticks(range(len(snap_names)), snap_names, rotation=45, ha="right", fontsize=8)
    plt.yticks(range(len(snap_names)), snap_names, fontsize=8)
    plt.colorbar(label="KS distance (degree dist)")
    plt.title("KS distances between out-degree distributions")
    plt.tight_layout()
    plt.savefig(plots_dir/"degree_distribution_ks_heatmap.png", dpi=180)
    plt.close()

    # bar spearman correlations
    plt.figure(figsize=(7, 4))
    plt.bar(range(len(corr_df)), corr_df["spearman"])
    plt.xticks(range(len(corr_df)), [f"{r.snap_i[-6:]}-{r.snap_j[-6:]}" for r in corr_df.itertuples()],
               rotation=45, ha="right", fontsize=8)
    plt.ylabel("Spearman correlation (nodewise out_degree)")
    plt.title("Nodewise out-degree correlation across snapshots")
    plt.tight_layout()
    plt.savefig(plots_dir/"nodewise_degree_spearman_across_snapshots.png", dpi=180)
    plt.close()

    # provenance: output hashes
    out_files = [p for p in out_dir.rglob("*") if p.is_file()]
    out_rows = [{"path": str(p.relative_to(out_dir)), "sha256": sha256_file(p)} for p in sorted(out_files)]
    pd.DataFrame(out_rows).to_csv(prov_dir/"sha256_index_outputs.csv", index=False)

if __name__ == "__main__":
    main()
